POST http://localhost:3001/persona
Content-Type: application/json

{
    "nombre": "daniela",
    "apellido": "de la Sierra",
    "ci": "47485475",
    "edad": 27
}

###

POST http://localhost:3001/domicilio/47485475
Content-Type: application/json

{
    "departamento": "Montevideo",
    "localidad": "Tres Cruces",
    "calle": "Avda. Uruguay",
    "nro": 1234,
    "apartamento": 1
}

###

GET http://localhost:3001/domicilios/47485475
Content-Type: application/json