POST http://localhost:3000/persona
Content-Type: application/json

{
    "nombre": "daniela",
    "apellido": "de la Sierra",
    "ci": "47485476",
    "edad": 27
}

###

POST http://localhost:3000/domicilio/47485476
Content-Type: application/json

{
    "departamento": "Montevideo",
    "localidad": "Tres Cruces",
    "calle": "Avda. Uruguay",
    "nro": 1234,
    "apartamento": 1
}

###

GET http://localhost:3000/domicilio/47485476
Content-Type: application/json

###

GET http://localhost:3000/domicilio
Content-Type: application/json